# Generated by Django 5.2.3 on 2025-07-11 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('identification', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(max_length=50, verbose_name='Fonte')),
                ('accepts_marketing', models.BooleanField(default=False, verbose_name='Aceita Marketing')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Gasto')),
                ('last_order_external_id', models.CharField(blank=True, max_length=100, verbose_name='Último Pedido')),
                ('first_interaction', models.DateTimeField(blank=True, null=True, verbose_name='Primeira Interação')),
                ('created_at_nuvemshop', models.DateTimeField(blank=True, null=True, verbose_name='Criado na Nuvemshop')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'unique_together': {('workspace', 'source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('address_type', models.CharField(choices=[('shipping', 'Entrega'), ('billing', 'Faturação')], max_length=10)),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='Andar/Complemento')),
                ('locality', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('province', models.CharField(max_length=100, verbose_name='Estado/Província')),
                ('country', models.CharField(default='BR', max_length=5, verbose_name='País')),
                ('zipcode', models.CharField(max_length=20, verbose_name='CEP')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace', verbose_name='Workspace')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='orders.customer')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número do Pedido')),
                ('source', models.CharField(max_length=50)),
                ('store_id', models.CharField(blank=True, max_length=30, verbose_name='ID da Loja Nuvemshop')),
                ('status', models.CharField(choices=[('pending_payment', 'Aguardando Pagamento'), ('processing', 'Em Processamento'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('paid', 'Pago'), ('open', 'Aberto')], db_index=True, default='pending_payment', max_length=30)),
                ('payment_status', models.CharField(choices=[('pending_payment', 'Aguardando Pagamento'), ('processing', 'Em Processamento'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('paid', 'Pago'), ('open', 'Aberto')], default='pending_payment', max_length=30, verbose_name='Status do Pagamento')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Forma de Pagamento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('shipping_status', models.CharField(choices=[('shipped', 'Enviado'), ('not_shipped', 'Não Enviado')], default='not_shipped', max_length=20, verbose_name='Status do Envio')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto Total')),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Frete')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Pago')),
                ('currency', models.CharField(default='BRL', max_length=10)),
                ('gateway', models.CharField(blank=True, max_length=100, verbose_name='Gateway')),
                ('gateway_id', models.CharField(blank=True, max_length=100, verbose_name='ID do Gateway')),
                ('order_created_at', models.DateTimeField(verbose_name='Criado em')),
                ('paid_by_customer', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pago pelo Cliente')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='orders.address')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-order_created_at'],
                'unique_together': {('workspace', 'source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('external_product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
