# Generated by Django 5.2.3 on 2025-07-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_address_country_remove_order_client_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Rastreio'),
        ),
    ]
