# Generated by Django 5.2.3 on 2025-07-11 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_carrier_order_tracking_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_carrier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_url',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='BR', max_length=5, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Andar/Complemento'),
        ),
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='customer',
            name='accepts_marketing',
            field=models.BooleanField(default=False, verbose_name='Aceita Marketing'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at_nuvemshop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criado na Nuvemshop'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_interaction',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Primeira Interação'),
        ),
        migrations.AddField(
            model_name='customer',
            name='identification',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_order_external_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Último Pedido'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Gasto'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='BRL', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto Total'),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gateway'),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID do Gateway'),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número do Pedido'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pago em'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_by_customer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pago pelo Cliente'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending_payment', 'Aguardando Pagamento'), ('processing', 'Em Processamento'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('paid', 'Pago'), ('open', 'Aberto')], default='pending_payment', max_length=30, verbose_name='Status do Pagamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('shipped', 'Enviado'), ('not_shipped', 'Não Enviado')], default='not_shipped', max_length=20, verbose_name='Status do Envio'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Frete'),
        ),
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='ID da Loja Nuvemshop'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_created_at',
            field=models.DateTimeField(verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='orders.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Aguardando Pagamento'), ('processing', 'Em Processamento'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('paid', 'Pago'), ('open', 'Aberto')], db_index=True, default='pending_payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Pago'),
        ),
    ]
