# Generated by Django 5.2.3 on 2025-07-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_shipping_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_carrier_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transportadora'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Rastreio'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tracking_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Rastreamento'),
        ),
    ]
