# Generated by Django 5.2.3 on 2025-07-11 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_shipping_carrier_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_carrier_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_tracking_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_tracking_url',
        ),
    ]
