# Generated by Django 5.2.3 on 2025-07-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_closed_at_order_paid_at_order_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fechado em (Origem)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pago em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Status de Envio'),
        ),
    ]
