# Generated by Django 5.2.3 on 2025-07-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_closed_at_alter_order_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=models.JSONField(blank=True, help_text='Informações adicionais sobre o pagamento, como método e status.', null=True, verbose_name='Detalhes do Pagamento'),
        ),
    ]
