# Generated by Django 5.2.3 on 2025-07-11 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('integration_type', models.CharField(choices=[('NUVEMSHOP', 'Nuvemshop'), ('MERCADOLIVRE', 'Mercadolivre'), ('WHATSAPP', 'Whatsapp')], max_length=20, verbose_name='Tipo de Integração')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Integração',
                'verbose_name_plural': 'Integrações',
            },
        ),
        migrations.CreateModel(
            name='NuvemshopIntegration',
            fields=[
                ('integration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.integration')),
                ('store_id', models.IntegerField(unique=True, verbose_name='ID da Loja Nuvemshop')),
                ('access_token', models.CharField(max_length=255, verbose_name='Token de Acesso')),
                ('webhook_secret', models.CharField(max_length=255, unique=True)),
                ('webhook_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Webhook')),
                ('webhook_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Criação do Webhook')),
                ('webhook_active', models.BooleanField(default=True, verbose_name='Webhook Ativo')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='URL do Webhook')),
                ('store_name', models.CharField(blank=True, max_length=255, verbose_name='Nome da Loja')),
                ('store_phone', models.CharField(blank=True, max_length=20, verbose_name='Número de Telefone')),
                ('store_email', models.EmailField(blank=True, max_length=254, verbose_name='Email da Loja')),
                ('store_domain', models.CharField(blank=True, max_length=255, verbose_name='Domínio da Loja')),
                ('store_document', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ da Loja')),
            ],
            options={
                'verbose_name': 'Integração Nuvemshop',
                'verbose_name_plural': 'Integrações Nuvemshop',
            },
            bases=('integrations.integration',),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50, verbose_name='Fonte do Evento')),
                ('event_type', models.CharField(max_length=100, verbose_name='Tipo do Evento')),
                ('payload', models.JSONField(verbose_name='Payload do Evento')),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('processed', 'Processado'), ('error', 'Erro')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhook',
                'ordering': ['-received_at'],
            },
        ),
    ]
