# Generated by Django 5.2.3 on 2025-06-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('integration_type', models.CharField(choices=[('NUVEMSHOP', 'Nuvemshop'), ('MERCADOLIVRE', 'Mercadolivre'), ('WHATSAPP', 'Whatsapp')], max_length=20, verbose_name='Tipo de Integração')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Integração',
                'verbose_name_plural': 'Integrações',
            },
        ),
    ]
