# Generated by Django 5.2.3 on 2025-07-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappIntegration',
            fields=[
                ('integration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.integration')),
                ('phone_number', models.CharField(max_length=100, unique=True, verbose_name='ID do Número de Telefone')),
                ('access_token', models.CharField(blank=True, max_length=255, verbose_name='Token de Acesso')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Token Secreto do Webhook')),
            ],
            options={
                'verbose_name': 'Integração WhatsApp',
                'verbose_name_plural': 'Integrações WhatsApp',
            },
            bases=('integrations.integration',),
        ),
    ]
