# Generated by Django 5.2.3 on 2025-06-28 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuvemshopIntegration',
            fields=[
                ('integration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.integration')),
                ('store_id', models.CharField(max_length=100, unique=True, verbose_name='ID da Loja Nuvemshop')),
                ('access_token', models.CharField(max_length=255, verbose_name='Token de Acesso')),
                ('webhook_secret', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Integração Nuvemshop',
                'verbose_name_plural': 'Integrações Nuvemshop',
            },
            bases=('integrations.integration',),
        ),
    ]
