# Generated by Django 5.2.3 on 2025-06-28 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_nuvemshopintegration'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50, verbose_name='Fonte do Evento')),
                ('event_type', models.CharField(max_length=100, verbose_name='Tipo do Evento')),
                ('payload', models.JSONField(verbose_name='Payload do Evento')),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('processed', 'Processado'), ('error', 'Erro')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhook',
                'ordering': ['-received_at'],
            },
        ),
    ]
