# Generated by Django 5.2.3 on 2025-07-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_whatsappintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappintegration',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número de Telefone'),
        ),
    ]
