# Generated by Django 5.2.3 on 2025-07-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_integration_name_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuvemshopintegration',
            name='store_document',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ da Loja'),
        ),
        migrations.AddField(
            model_name='nuvemshopintegration',
            name='store_domain',
            field=models.CharField(blank=True, max_length=255, verbose_name='Domínio da Loja'),
        ),
        migrations.AddField(
            model_name='nuvemshopintegration',
            name='store_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email da Loja'),
        ),
        migrations.AddField(
            model_name='nuvemshopintegration',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome da Loja'),
        ),
        migrations.AddField(
            model_name='nuvemshopintegration',
            name='store_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de Telefone'),
        ),
        migrations.AddField(
            model_name='nuvemshopintegration',
            name='webhook_active',
            field=models.BooleanField(default=True, verbose_name='Webhook Ativo'),
        ),
        migrations.AddField(
            model_name='nuvemshopintegration',
            name='webhook_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Criação do Webhook'),
        ),
        migrations.AddField(
            model_name='nuvemshopintegration',
            name='webhook_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Webhook'),
        ),
    ]
