# Generated by Django 5.2.3 on 2025-07-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_nuvemshopintegration_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuvemshopintegration',
            name='store_id',
            field=models.IntegerField(max_length=100, unique=True, verbose_name='ID da Loja Nuvemshop'),
        ),
    ]
