# Generated by Django 5.2.3 on 2025-07-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_nuvemshopintegration_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuvemshopintegration',
            name='store_id',
            field=models.IntegerField(unique=True, verbose_name='ID da Loja Nuvemshop'),
        ),
    ]
